"""add email column to employee

Revision ID: 35f73259e918
Revises: 0f0981c6fd25
Create Date: 2026-02-15 03:07:02.890656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f73259e918'
down_revision: Union[str, Sequence[str], None] = '0f0981c6fd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add column as nullable
    op.add_column(
        'employee',
        sa.Column('email', sa.String(length=50), nullable=True)
    )

    # Step 2: Fill existing rows with default value
    op.execute("UPDATE employee SET email = 'temp@example.com'")

    # Step 3: Make column NOT NULL
    op.alter_column('employee', 'email', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
